//
// Created by fortune on 2/28/26.
//

#ifndef WEB_SERVER_REQUEST_H
#define WEB_SERVER_REQUEST_H

enum http_methods {
    HTTP_METHOD_GET,
    HTTP_METHOD_POST,
    HTTP_METHOD_PUT,
    HTTP_METHOD_DELETE,
    HTTP_METHOD_PATCH,
    HTTP_METHOD_HEAD,
    HTTP_METHOD_OPTIONS,
    HTTP_METHOD_TRACE,
    HTTP_METHOD_CONNECT,
    HTTP_METHOD_UNKNOWN
}

#endif //WEB_SERVER_REQUEST_H